### ISSUE TITLE
Scatter with pointsize

### ISSUE THREAD

**Issue by SteffenPL** [JuliaImGui/ImPlot.jl#1]
Thanks for the great package!

Is it possible to add functionality to define the size of scatter points individually? 
Or is there a way to archive this with the current package?

**Comment by wsphillips** [comment]
Sorry for taking so long to comment: Do you mean you want individual data points to be sized differently in a single set of data? I haven't personally tried this, but my guess is you might have to pre-filter the data to accomplish this (e.g. begin plot, then plot all points size #1, plot points of size #2... end plot) while modifying the styling between the scatter plot calls.

Note also the plot styling is in the process of getting fleshed out more and more upstream in the implot C++ library.

**Comment by wsphillips** [comment]
You should be able to get this behavior by adapting the code [here](https://github.com/wsphillips/ImPlot.jl/blob/10f0ec2262e0d69357dcd1a48dccb8a41c5c5500/demo/implot_demo.jl#L824-L871). (It's generally what I described before)

Specifically, make a loop that changes marker size via `ImPlot.SetNextMarkerStyle` on each iteration and subsequently calls `ImPlot.PlotScatter`. The data passed to `PlotScatter` should correspond to the points you want at each particular size.

Edit: Note you'll need to be on `main` branch for this to work.

**Comment by SteffenPL** [comment]
Thanks a lot!
