### ISSUE TITLE
ImPlot example with state-management and Renderer

### ISSUE THREAD

**Issue by sairus7** [JuliaImGui/ImPlot.jl#10]
https://gist.github.com/sairus7/19778c05ffba7c677a3414f752a0f9cb

Just rewrote the example from [demo/example_plots.jl](https://github.com/wsphillips/ImPlot.jl/blob/master/demo/example_plots.jl), using Renderer to hide ImGUI boilerplate code, as explained [here](https://github.com/Gnimuc/CImGui.jl/discussions/39).

However, there are some things I don't like in this example:
- store state variables inside a structure - it will be very bloated for complex GUI - is there some `static` macro in Julia, or `isdefined` for local variables?
- passing state with field destructuring - maybe it's fine to write `state.` in front of all data variables.

**Comment by Gnimuc** [comment]
> * store state variables inside a structure - it will be very bloated for complex GUI - is there some `static` macro in Julia, or `isdefined` for local variables?

you may find [this](https://github.com/Gnimuc/CSyntax.jl/blob/master/src/CStatic.jl) useful. I prefer [Redux.jl](https://github.com/Gnimuc/Redux.jl) for something scalable, but it needs even more boilerplate code.

**Comment by sairus7** [comment]
@Gnimuc thanks for the links!
Using `@cstatic` has some limitations: 
1) you cannot write complex initialization code that should be run only at startup,
2) it is just one-liners for variables, and if there are many variables, the code becomes messy:
```julia
using CImGui.CSyntax.CStatic
function foo()
    @cstatic a, b, c = 1, zeros(3), [x^2 for x in 1:5] begin
        a += 100
        b .+= 10
        c .+= 1
        println("$a,$b,$c")
    end
end
function loop()
    for i=1:10
        foo()
    end
end

loop()
```
I don't quite understand strong parts of Redux from the link above.

Can you point me to some complex ImGui projects and how do they actually handle state-sharing between a whole lot of GUI components in the scene, if they interact with each other?

**Comment by wsphillips** [comment]
Closing this. These are CStatic / ImGui questions.
