### ISSUE TITLE
Plot styles missing (marker, color, etc.)

### ISSUE THREAD

**Issue by sairus7** [JuliaImGui/ImPlot.jl#11]
I've tried to repeat simple plots from [c++ demo](https://traineq.org/implot_demo/src/implot_demo.html), namely [Line Plots](https://github.com/epezent/implot/blob/master/implot_demo.cpp#L235), but could not find some methods, like setting line and marker styles. 

First, there is no `ImPlotMarker_Circle` exported, so I looked at source and found it here: `ImPlot.LibCImPlot.ImPlotMarker_Circle`

Second, there is no `SetNextMarkerStyle` method in source, so I've tried to define my own ccall method for `ImPlot.LibCImPlot.libcimplot` library:
```julia
function SetNextMarkerStyle(style)
    ccall((:ImPlot_SetNextMarkerStyle, ImPlot.LibCImPlot.libcimplot), Cvoid, (Cint,), style)
end
```
But it didn't find `:ImPlot_SetNextMarkerStyle` from dll: 
```
could not load symbol "ImPlot_SetNextMarkerStyle": The specified procedure could not be found.
```

Here is my code:

```julia
include("Renderer.jl")

using .Renderer
using CImGui
using CImGui.CSyntax
using CImGui.CSyntax.CStatic
import CImGui.LibCImGui: ImGuiCond_Always, ImGuiCond_Once
using ImPlot

import Base.@kwdef

@kwdef struct MyState1
    xs1 = zeros(Float32, 1001)
    ys1 = zeros(Float32, 1001)
    xs2 = zeros(11)
    ys2 = zeros(11)
end

function update!(state::MyState1)
    DEMO_TIME = CImGui.GetTime()

    for i = 1:length(state.xs1)
        state.xs1[i] = i * 0.001;
        state.ys1[i] = 0.5 + 0.5 * sin(50 * (state.xs1[i] + DEMO_TIME / 10));
    end
    for i = 1:length(state.xs2)
        state.xs2[i] = i * 0.1;
        state.ys2[i] = state.xs2[i] * state.xs2[i];
    end
end


function SetNextMarkerStyle(style) # this function results with error
    ccall((:ImPlot_SetNextMarkerStyle, ImPlot.LibCImPlot.libcimplot), Cvoid, (Cint,), style)
end

function ui(state::MyState1)
    update!(state)
    if ImPlot.BeginPlot("Line Plot", "x", "f(x)", CImGui.ImVec2(-1,300))
        ImPlot.PlotLine(state.xs1, state.ys1); # "sin(x)", 
        SetNextMarkerStyle(ImPlot.LibCImPlot.ImPlotMarker_Circle);
        ImPlot.PlotLine(state.xs2, state.ys2); # "x^2", 
        ImPlot.EndPlot();
    end
end

state = MyState1()
Renderer.render(()->ui(state), width = 360, height = 480, title = "A simple UI")
```

I'm using Renderer.jl file from here: https://github.com/Gnimuc/CImGui.jl/tree/cf9d4adc5f5c4134ec72cbf3ed366d16e61adaaf/examples 

So, for now I just have two line plots with single color:
![image](https://user-images.githubusercontent.com/20798349/111028211-40658f80-8406-11eb-95ab-0633f413b7dc.png)

**Comment by wsphillips** [comment]
By default all the possible flags are not imported. You can add whatever you need using a statement like:
```
import ImPlot.LibCImPlot.ImPlotMarker_Circle
```

...after which you can refer to it directly. 

The reason you cannot access that function is because the current stable release uses an older version of implot. However the development branch is running on newer implot binaries and has it available in the LibCImPlot submodule. If you want to use it you can `]add https://github.com/wsphillips/ImPlot.jl#master`

**Comment by wsphillips** [comment]
I added a note about the version disparity to the [README](https://github.com/wsphillips/ImPlot.jl/commit/bcf838585f4d8a6462c7dc1dcdb9eb2b98ab2616)

**Comment by sairus7** [comment]
I' ve added master branch, and now it is failing and closing Julia terminal, with the following message:
```
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x70c459b2 -- _ZNK12ImGuiStorage6GetIntEji at C:\Users\user\.julia\artifacts\d94c52f336f108dde7d330d65593b7495aaf6615\bin\libimgui-cpp.dll (unknown line)
in expression starting at none:0
_ZNK12ImGuiStorage6GetIntEji at C:\Users\user\.julia\artifacts\d94c52f336f108dde7d330d65593b7495aaf6615\bin\libimgui-cpp.dll (unknown line)
__fu2_GImGui at C:\Users\user\.julia\artifacts\bc6d4eab4f69b524f9d68ed421348827a9def601\bin\libcimplot.dll (unknown line)
ImPlot_BeginPlot at C:\Users\user\.julia\artifacts\bc6d4eab4f69b524f9d68ed421348827a9def601\bin\libcimplot.dll (unknown line)
BeginPlot at C:\Users\user\.julia\packages\ImPlot\UDe1S\src\libcimplot\libcimplot_api.jl:25
#BeginPlot#1 at C:\Users\user\.julia\packages\ImPlot\UDe1S\src\ImPlot.jl:27 [inlined]
BeginPlot at C:\Users\user\.julia\packages\ImPlot\UDe1S\src\ImPlot.jl:27 [inlined]
ui at C:\Users\user\.julia\dev\MyPlayground\test\implot_demo_lines.jl:35
#2 at C:\Users\user\.julia\dev\MyPlayground\test\implot_demo_lines.jl:44
renderloop at C:\Users\user\.julia\dev\MyPlayground\test\Renderer.jl:62
#4 at .\task.jl:356
unknown function (ip: 000000002D5B0193)
jl_apply at /cygdrive/d/buildbot/worker/package_win64/build/src\julia.h:1690 [inlined]
start_task at /cygdrive/d/buildbot/worker/package_win64/build/src\task.c:707
Allocations: 3175483 (Pool: 3174726; Big: 757); GC: 4
```
Not very informative to me, but it points to lines:
```julia
if ImPlot.BeginPlot("Line Plot", "x", "f(x)", CImGui.ImVec2(-1,300))
```
and
```julia
Renderer.render(()->ui(state), width = 360, height = 480, title = "A simple UI")
```
Looks like just the first call to ImPlot is failing.

Tried with Julia 1.5.2 and 1.6.0-rc2, Win 10 x64

**Comment by sairus7** [comment]
Adding these lines to Renderer.jl, function `init_renderer` solved the problem:

```julia
    ctxp = ImPlot.CreateContext()
    ImPlot.SetImGuiContext(ctx)
```
Now I'm trying to figure out, what types should I pass into 
`SetNextMarkerStyle(::Any, ::Any, ::Any, ::Any, ::Any)`

**Comment by wsphillips** [comment]
I suggest looking at the argument types in the [headers for implot](https://github.com/epezent/implot/blob/v0.8/implot.h) and trying to replicate it. It looks like default arguments are usually `IMPLOT_AUTO` and `IMPLOT_AUTO_COL` which are both defined for you in the `LibCImPlot` submodule.

**Comment by sairus7** [comment]
Yes, from [implot.h](https://github.com/epezent/implot/blob/v0.8/implot.h#L598):
```cpp
IMPLOT_API void SetNextMarkerStyle(ImPlotMarker marker = IMPLOT_AUTO, float size = IMPLOT_AUTO, const ImVec4& fill = IMPLOT_AUTO_COL, float weight = IMPLOT_AUTO, const ImVec4& outline = IMPLOT_AUTO_COL);
```
however, in my atrifacts there is another source `cimplot.h` with this line:
```cpp
CIMGUI_API void ImPlot_SetNextMarkerStyle(ImPlotMarker marker,float size,const ImVec4 fill,float weight,const ImVec4 outline);
```
And in [libcimplot_api.jl](https://github.com/wsphillips/ImPlot.jl/blob/master/src/libcimplot/libcimplot_api.jl#L1193) I see:
```julia
function SetNextMarkerStyle(marker, size, fill, weight, outline)
    ccall((:ImPlot_SetNextMarkerStyle, libcimplot), Cvoid, (ImPlotMarker, Cfloat, Cint, Cfloat, Cint), marker, size, fill, weight, outline)
end
```

There are different types in function signatures, looks like an error in api:
1) `(ImPlotMarker, Cfloat, Cint, Cfloat, Cint)` - from `libcimplot_api.jl`
2) `(ImPlotMarker, Cfloat, ImVec4, Cfloat, ImVec4)` - the one actually used

I get it to work with redefined ccall method:
```julia
function SetNextMarkerStyle_my(
    marker = ImPlot.LibCImPlot.IMPLOT_AUTO, 
    size = ImPlot.LibCImPlot.IMPLOT_AUTO, 
    fill = ImPlot.LibCImPlot.IMPLOT_AUTO_COL, 
    weight = ImPlot.LibCImPlot.IMPLOT_AUTO,
    outline = ImPlot.LibCImPlot.IMPLOT_AUTO_COL
    )
    ccall(
        (:ImPlot_SetNextMarkerStyle, ImPlot.LibCImPlot.libcimplot), Cvoid, 
        (ImPlot.LibCImPlot.ImPlotMarker, Cfloat, CImGui.ImVec4, Cfloat, CImGui.ImVec4), marker, size, fill, weight, outline
    )
end
```

**Comment by sairus7** [comment]
There are other problems with colormap - it the demo there is automatic color switch between different lines, but here It draws in one color only.

So I can only set marker color by hand:
![image](https://user-images.githubusercontent.com/20798349/111036091-87677b00-842e-11eb-922b-64e1d11c4aa8.png)

And If I add `SetNextLineStyle_my` method (there is the same function signature error in api), then all lines become red (why?):
![image](https://user-images.githubusercontent.com/20798349/111036149-d01f3400-842e-11eb-95c1-e69435aed819.png)

Source:
```julia
function SetNextLineStyle_my(
    col = ImPlot.LibCImPlot.IMPLOT_AUTO_COL, 
    weight = ImPlot.LibCImPlot.IMPLOT_AUTO
    )
    ccall(
        (:ImPlot_SetNextLineStyle, ImPlot.LibCImPlot.libcimplot), Cvoid, 
        (CImGui.ImVec4, Cfloat), col, weight)
end

function ui(state::MyState1)
    update!(state)
    ImPlot.SetColormap(ImPlot.LibCImPlot.ImPlotColormap_Default)
    if ImPlot.BeginPlot("Line Plot!", "x", "f(x)", CImGui.ImVec2(-1,300))
        ImPlot.PlotLine(state.xs1, state.ys1); # "sin(x)", 
        SetNextLineStyle_my(CImGui.ImVec4(1,0,0,1)) # all in red ?!
        SetNextMarkerStyle_my(
            ImPlot.LibCImPlot.ImPlotMarker_Circle,
            ImPlot.LibCImPlot.IMPLOT_AUTO,
            CImGui.ImVec4(1,0,0,1),
            ImPlot.LibCImPlot.IMPLOT_AUTO,
            CImGui.ImVec4(1,0,0,1)
        );
        ImPlot.PlotLine(state.xs2, state.ys2); # "x^2", 
        ImPlot.EndPlot();
    end
end
```

**Comment by sairus7** [comment]
Should I try to fix api methods by hand and make a PR, or it is code-generated and should be fixed somewhere else?

**Comment by sairus7** [comment]
@wsphillips should I try to fix api methods by hand and make a PR, or it is code-generated and should be fixed somewhere else?

**Comment by wsphillips** [comment]
If you're finding method signature problems in the low-level ccall wrappers, that's expected and usually something that has to be adjusted by hand on a case-by-case basis. It happens because Clang.jl can't discriminate how certain C argument types should be represented on the Julia side, and there's really no way around it.

**Comment by wsphillips** [comment]
> ```c++
> IMPLOT_API void SetNextMarkerStyle(ImPlotMarker marker = IMPLOT_AUTO, float size = IMPLOT_AUTO, const ImVec4& fill = IMPLOT_AUTO_COL, float weight = IMPLOT_AUTO, const ImVec4& outline = IMPLOT_AUTO_COL);
> ```
> however, in my atrifacts there is another source `cimplot.h` with this line:
> ```c++
> CIMGUI_API void ImPlot_SetNextMarkerStyle(ImPlotMarker marker,float size,const ImVec4 fill,float weight,const ImVec4 outline);
> ```

These are equivalent. One is from the original C++ and the other is the generated C wrappers that we're "actually" wrapping. I refer you to the C++ header because it usually contains default values too :smile: 

> And in [libcimplot_api.jl](https://github.com/wsphillips/ImPlot.jl/blob/master/src/libcimplot/libcimplot_api.jl#L1193) I see:
> 
> ```julia
> function SetNextMarkerStyle(marker, size, fill, weight, outline)
>     ccall((:ImPlot_SetNextMarkerStyle, libcimplot), Cvoid, (ImPlotMarker, Cfloat, Cint, Cfloat, Cint), marker, size, fill, weight, outline)
> end
> ```

Yes. The arguments weren't parsed correctly during wrapper generation, as mentioned in the comment above. Clang.jl often inserts a Cint when it isn't sure (in this case because they're types from another header file). The solution is to do exactly what you did.

**Comment by sairus7** [comment]
Ok, I will make PR to fix that (probably find all `ImVec4`, `ImVec2`, etc.).

I've read there is an ongoing work to rework Clang to handle forward decls: https://github.com/Gnimuc/CImGui.jl/issues/38#issuecomment-768740936
Is it related so some of these problems, so we can just have errors fixed automatically after this rework?

Or there is some list of cherry-picked changes that is applied every time a new wrapper code is generated?

**Comment by wsphillips** [comment]
> 
> ```julia
> function SetNextLineStyle_my(
>     col = ImPlot.LibCImPlot.IMPLOT_AUTO_COL, 
>     weight = ImPlot.LibCImPlot.IMPLOT_AUTO
>     )
>     ccall(
>         (:ImPlot_SetNextLineStyle, ImPlot.LibCImPlot.libcimplot), Cvoid, 
>         (CImGui.ImVec4, Cfloat), col, weight)
> end
> 
> function ui(state::MyState1)
>     update!(state)
>     ImPlot.SetColormap(ImPlot.LibCImPlot.ImPlotColormap_Default)
>     if ImPlot.BeginPlot("Line Plot!", "x", "f(x)", CImGui.ImVec2(-1,300))
>         ImPlot.PlotLine(state.xs1, state.ys1); # "sin(x)", 
>         SetNextLineStyle_my(CImGui.ImVec4(1,0,0,1)) # all in red ?!
>         SetNextMarkerStyle_my(
>             ImPlot.LibCImPlot.ImPlotMarker_Circle,
>             ImPlot.LibCImPlot.IMPLOT_AUTO,
>             CImGui.ImVec4(1,0,0,1),
>             ImPlot.LibCImPlot.IMPLOT_AUTO,
>             CImGui.ImVec4(1,0,0,1)
>         );
>         ImPlot.PlotLine(state.xs2, state.ys2); # "x^2", 
>         ImPlot.EndPlot();
>     end
> end
> ```

You're passing an ImVec4 that's RGBA values are (1,0,0,1) which is indeed red. Perhaps you're overriding the color map?  It looks like the function you really want is `PushColormap(ImPlotColormap colormap)` prior to starting your line plots. I think if you use IMPLOT_AUTO_COL for the line color it will do what you want. And perhaps `NextColormapColor()` might be useful if that doesn't work.

**Comment by sairus7** [comment]
Another problem is with `@cenum` flags - if I use a bitwise combination of values, it doesn't work with Int32:

```
function test_flags()
    # flags = ImPlotAxisFlags_NoTickLabels # working
    flags = ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_NoTickMarks # ! error
    # flags = ImPlot.LibCImPlot.ImPlotAxisFlags(ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_NoTickMarks) # working
    if ImPlot.BeginPlot("##example", "", "", CImGui.ImVec2(-1, 300),  
            y_flags = flags
        )
        @cstatic x, y = collect(1:100), rand(100) begin
            ImPlot.PlotLine(x, y)
        end
        ImPlot.EndPlot()
    end
end
```


```julia
┌ Error: Error in renderloop!
│   exception = TypeError: in keyword argument y_flags, expected ImPlot.LibCImPlot.ImPlotAxisFlags, got a value of type Int32
└ @ TestGui.EcgGui.Renderer c:\Users\user\.julia\dev\TestGui\src\Renderer.jl:85
```

UPD: it works only if I declare its type like this: 
```
flags = ImPlot.LibCImPlot.ImPlotAxisFlags(ImPlotAxisFlags_NoTickLabels | ImPlotAxisFlags_NoTickMarks)
```

**Comment by sairus7** [comment]
UPD-2: This is expected behaviour in C++,  and flag cpp types are actually `typedef int`: https://github.com/epezent/implot/blob/master/implot.h#L56

**Comment by wsphillips** [comment]
I know it maps more closely to C/C++, but I disagree with the idea of aliasing all the flag types as Cint. I would prefer to handle this on our end with a handful of additional dispatches for bitwise operators and possibly `convert`
