### ISSUE TITLE
exception = UndefVarError: ShowStyleEditor not defined

### ISSUE THREAD

**Issue by jhgorse** [JuliaImGui/ImPlot.jl#21]
ShowStyleEditor not defined for ImPlot:
https://github.com/wsphillips/ImPlot.jl/blob/c64f66c5ac1fd9e227799a1aa9381362f02fb1fd/demo/implot_demo.jl#L338

But ShowStyleEditor is defined for CImGui and works.

```
julia> include("play.jl")
show (generic function with 1 method)

julia> show()
Task (runnable) @0x0000000149836e00

julia> ┌ Error: Error in renderloop!
│   exception = UndefVarError: ShowStyleEditor not defined
└ @ Main.Renderer ~/Documents/work2016/das/data/Renderer.jl:85

Stacktrace:
 [1] ShowDemoWindow()
   @ Main ~/Documents/work2016/das/data/play.jl:333
 [2] #3
   @ ~/Documents/work2016/das/data/play.jl:1942 [inlined]
 [3] renderloop(window::GLFW.Window, ctx::Ptr{CImGui.LibCImGui.ImGuiContext}, ui::var"#3#4", hotloading::Bool)
   @ Main.Renderer ~/Documents/work2016/das/data/Renderer.jl:70
 [4] (::Main.Renderer.var"#4#5"{Bool, var"#3#4", Ptr{CImGui.LibCImGui.ImGuiContext}, GLFW.Window})()
```

**Comment by jhgorse** [comment]
Works when you run from demo.jl, not from implot_demo.jl.

**Comment by jhgorse** [comment]
@wsphillips consider changing the Readme from 

```
include("implot_demo.jl")
show()
```
Select Realtime and it crashes.

```
julia> include("/Users/jhg/.julia/packages/ImPlot/kI3XA/demo/implot_demo.jl")
WARNING: replacing module Renderer.
WARNING: replacing module MyImPlot.
WARNING: replacing module Huge.
show (generic function with 1 method)

julia> show()
Task (runnable) @0x000000014ec30e80

julia> ┌ Error: Error in renderloop!
│   exception = type DataType has no field mutable
└ @ Main.Renderer ~/.julia/packages/ImPlot/kI3XA/demo/Renderer.jl:85

Stacktrace:
 [1] getproperty
   @ ./Base.jl:37 [inlined]
 [2] PlotShaded(structvec::Vector{ImVec2}, xfield::Symbol, yfield::Symbol, y_ref::Int64; count::Int64, offset::Int64, stride::Int64, label_id::String)
   @ ImPlot ~/.julia/packages/ImPlot/kI3XA/src/shaded.jl:111
 [3] ShowDemoWindow()
   @ Main ~/.julia/packages/ImPlot/kI3XA/demo/implot_demo.jl:810
 [4] (::var"#49#50")()
   @ Main ~/.julia/packages/ImPlot/kI3XA/demo/implot_demo.jl:1940
 [5] #invokelatest#2
   @ ./essentials.jl:716 [inlined]
 [6] invokelatest
   @ ./essentials.jl:714 [inlined]
 [7] renderloop(window::GLFW.Window, ctx::Ptr{CImGui.LibCImGui.ImGuiContext}, ui::var"#49#50", hotloading::Bool)
   @ Main.Renderer ~/.julia/packages/ImPlot/kI3XA/demo/Renderer.jl:70
 [8] (::Main.Renderer.var"#4#5"{Bool, var"#49#50", Ptr{CImGui.LibCImGui.ImGuiContext}, GLFW.Window})()
```

to `julia demo.jl` which works without issue on macOS latest.

**Comment by wsphillips** [comment]
What version of ImPlot.jl are you using? Did you mean to close this issue?

Although it certainly "works", `demo.jl` should probably be removed from the repo entirely since it gives a false sense of what's tested to be working from the Julia side of things.  `demo.jl` calls the precompiled C++ demo, rather than using the Julia API to reproduce the demo from scratch as we do in `implot_demo.jl` If something is not working in `implot_demo.jl` then it's not guaranteed to work  if you try to implement something comparable yourself in Julia.

That being said, realtime plots _should_ work and for me they do on Linux using v0.2.0 of `ImPlot.jl` and v1.79 of `CImGui.jl`. If it's platform-specific that's going to be hard since I don't personally have a Mac to test it on. @Gnimuc develops on MacOS and might be able to check for you, though. 

`ShowStyleEditor` is not working because of an overlooked export. You can get it to work by changing the line where it's used in `implot_demo.jl` to:

```julia
        if show_implot_style_editor
            CImGui.SetNextWindowSize(ImVec2(415,762), ImGuiCond_Appearing)
            @c CImGui.Begin("Style Editor (ImPlot)", &show_implot_style_editor)
            ImPlot.LibCImPlot.ShowStyleEditor(C_NULL) # added submodule and default null arg
            CImGui.End()
        end
```

**Comment by jhgorse** [comment]
@wsphillips how do I check what versions I have? I am new here and the last time I looked I became confused looking at github and the various packages and releases and printed output upon running the demo.

So demo.jl doing "@c ImPlot.LibCImPlot.ShowDemoWindow(&show_demo_window)" is a precompiled C-wrapped C++ demo? Interesting.

And yes, it was running on macOS latest and the 1.7 Julia. I can get the other details tonight when I get back to that computer.

Things work fine on Windows 10, Julia 1.6 stable and the regular packages available via `pkg`.

**Comment by wsphillips** [comment]
Ok, the first thing I would suggest is sticking to Julia 1.6 on your Mac setup. Are you using a newer M1 system?

If you're installing the packages via the package manager you ought to be fine. If you ever want to check what package versions you have, you can type `]st` from your Julia REPL to print out the top level packages installed in your current Julia environment.

**Comment by jhgorse** [comment]
I am running Intel I7.

Will regress to 1.6.

```
(@v1.7) pkg> st
      Status `~/.julia/environments/v1.7/Project.toml`
  [5d785b6c] CImGui v1.79.0
  [336ed68f] CSV v0.9.1
  [a93c6f00] DataFrames v1.2.2
  [28b8d3ca] GR v0.58.1
  [4b11ee91] Gaston v1.0.4
  [e8efc688] ImPlot v0.2.0
  [d0351b0e] InspectDR v0.4.3
  [91a5bcdd] Plots v1.21.3
  [efcf1570] Setfield v0.7.1
```

**Comment by jhgorse** [comment]
Working with this configuration on Intel i7 with latest macOS:

```
(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
  [5d785b6c] CImGui v1.79.0
  [336ed68f] CSV v0.9.2
  [e8efc688] ImPlot v0.2.0
  [91a5bcdd] Plots v1.21.3
  [efcf1570] Setfield v0.7.1
```
