### ISSUE TITLE
Multiple Y-Axes

### ISSUE THREAD

**Issue by oheil** [JuliaImGui/ImPlot.jl#3]
I try to plot a plot with multiple y-axes like in the demo.jl. This is how I try to do it:
```
y1 = rand(1000)
y2 = rand(1000).+2.0
ImPlot.SetNextPlotLimits(0.0,1000,0.0,4.0,ImGuiCond_Always)
ImPlot.SetNextPlotLimitsY(0.0, 1.0, ImGuiCond_Always,1)
ImPlot.SetNextPlotLimitsY(0.0, 4.0, ImGuiCond_Always,2)
if ImPlot.BeginPlot("##line", "x", "y", CImGui.ImVec2(-1,-1); flags = ImPlot.ImPlotFlags_YAxis2 )
	ImPlot.PlotLine(y1)
	ImPlot.SetPlotYAxis(2)
	ImPlot.PlotLine(y2)
	ImPlot.EndPlot()
end
```
The second y-axis isn't plotted. Any idea what I do wrong?

**Comment by wsphillips** [comment]
not sure, I can try to work it out in the coming days since I have a bit of time for this project again

**Comment by wsphillips** [comment]
See examples in `gen/implot_demo.jl` added in #14 

Edit: Note you'll need to be using `main` branch until we tag a release.
