### ISSUE TITLE
Tag ImPlot v0.4.0

### ISSUE THREAD

**Issue by sairus7** [JuliaImGui/ImPlot.jl#30]
Can we tag and register current master version of ImPlot as 0.4.0?
@JamesWrigley @wsphillips 

Related issue: https://github.com/wsphillips/ImPlot.jl/issues/29

**Comment by JamesWrigley** [comment]
Yep, I think it's ready to be tagged :+1:

**Comment by sairus7** [comment]
@wsphillips can you run the command `@JuliaRegistrator register` on the last commit?

**Comment by sairus7** [comment]
Oh, I think I did it just now)

**Comment by sairus7** [comment]
I've made a new tag and github release, so I'm closing this and closing #29

**Comment by JamesWrigley** [comment]
The bot does less validation than I thought :laughing:
