### ISSUE TITLE
missing flag ImPlotAxisFlags_NoTickLabels and omitting x-label not possible

### ISSUE THREAD

**Issue by oheil** [JuliaImGui/ImPlot.jl#4]
This flag is used in
https://github.com/epezent/implot/blob/master/implot_demo.cpp
for the Realtime Plots and it seems to miss here.

And omitting an axis label by setting it to NULL/C_NULL is not possible, too.
Again see Realtime Plots in implot_demo.cpp:
`if (ImPlot::BeginPlot("##Scrolling", NULL, NULL, ImVec2(-1,150), 0, rt_axis, rt_axis | ImPlotAxisFlags_LockMin)) {`
Setting parameter x_label to NULL does remove it and uses the free space for the plot.
This is not possible here. Setting it to an empty string does use an empty string for the label and doesn't use the free space for the plot. Setting it to C_NULL produces an error.

I think it would be a good idea to implement the implot_demo.cpp in Julia instead of just calling ImPlot_ShowDemoWindow from Julia. This would be a proper test case for ImPlot.jl

**Comment by oheil** [comment]
Used ImPlot version is something 0.6 (before 0.7), this has changed in recent versions.
Any plans to keep track with ImPlot updates?

**Comment by wsphillips** [comment]
This is because the underlying binaries are from implot v0.4 before these flags were added. I do intend to upgrade the version of implot and will try to get to it this weekend (hopefully direct to latest tagged release == v0.8)

**Comment by wsphillips** [comment]
Master is now on implot v0.8 via #8 and should have the latest flags available according to [this implot commit ](https://github.com/epezent/implot/tree/a9d334791563cdaf9bd0bf7f9899a67bcd03179b)
Let me know if the issue still persists.

**Comment by oheil** [comment]
ImPlotAxisFlags_NoTickLabels is now working as expected.
Using C_NULL to remove the free space is not yet possible.
I had some more issues for which I provide PR, hold on...
