### ISSUE TITLE
update to cimplot v0.8

### ISSUE THREAD

**Issue by yadmtr** [JuliaImGui/ImPlot.jl#7]
Аre you planning to update to cimplot v0.8?

**Comment by wsphillips** [comment]
Yes, I'm just busy at the moment. The binaries have been built for v0.8 at https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl

The wrappers need to be updated to match the changes to the API. If someone wants to lend a hand, it would be very appreciated. Otherwise, I'll get to it as time permits.

**Comment by wsphillips** [comment]
Working on this... #8

**Comment by wsphillips** [comment]
Support for implot v0.8 is merged, but some of the new plot types don't have high-level convenience functions yet. Once that gets done I'll tag a new version. If you want to play with it right now do `]add https://github.com/wsphillips/ImPlot.jl#master`

**Comment by sefffal** [comment]
Thanks for the great package! Not to sound greedy, but any chance we could also get implot v0.9 at the same time? The performance improvements to heatmaps would be really nice to have.

I'm happy to contribute as well if you point me to the right places.

**Comment by wsphillips** [comment]
implot v0.9 hasn't been finished/tagged upstream yet, but when it is we can make that move. If you're looking to contribute, we need convenience functions for the plot types/features that were added to implot between v0.4 and v0.8. A lot of it is just boiler plate, but I just haven't had enough time to do it myself. When those are done I can tag the next version of ImPlot.jl

**Comment by sairus7** [comment]
I think a list of convenience functions not covered with the current API would be helpful. 

Also, there are some `LibCImPlot` functions which do not need any convenience functions, but are not exported by `ImPlot` - a list of them would be helpful too.

And also, there are some errors in `ccall` signatures, for which I don't know how to deal with: https://github.com/wsphillips/ImPlot.jl/issues/11#issuecomment-798514009
Probably, this is an error in generator.

Actually, I think we can start rewriting existing [implot_demo.cpp](https://github.com/epezent/implot/blob/master/implot_demo.cpp) to check what functions are missing in the first place. I just don't know which version of that demo should we rewrite, and how to compare results.

**Comment by wsphillips** [comment]
`master` now on implot v0.8
